### ISSUE TITLE
module 'include' has no attribute 'get_single_refs

### ISSUE THREAD

**Issue by slientnight** [menandmice/ansible-module#1]
I am running into the below issue when trying to create a record.
`The full traceback is:
Traceback (most recent call last):
  File "/home/hollisma/.ansible/tmp/ansible-tmp-1622855131.6394677-110818-22478518117393/AnsiballZ_mm_dnsrecord.py", line 102, in <module>
    _ansiballz_main()
  File "/home/hollisma/.ansible/tmp/ansible-tmp-1622855131.6394677-110818-22478518117393/AnsiballZ_mm_dnsrecord.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/hollisma/.ansible/tmp/ansible-tmp-1622855131.6394677-110818-22478518117393/AnsiballZ_mm_dnsrecord.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.mm_dnsrecord', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_mm_dnsrecord_payload_926tdi80/ansible_mm_dnsrecord_payload.zip/ansible/modules/mm_dnsrecord.py", line 377, in <module>
  File "/tmp/ansible_mm_dnsrecord_payload_926tdi80/ansible_mm_dnsrecord_payload.zip/ansible/modules/mm_dnsrecord.py", line 373, in main
  File "/tmp/ansible_mm_dnsrecord_payload_926tdi80/ansible_mm_dnsrecord_payload.zip/ansible/modules/mm_dnsrecord.py", line 260, in run_module
AttributeError: module 'include' has no attribute 'get_single_refs'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/hollisma/.ansible/tmp/ansible-tmp-1622855131.6394677-110818-22478518117393/AnsiballZ_mm_dnsrecord.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/hollisma/.ansible/tmp/ansible-tmp-1622855131.6394677-110818-22478518117393/AnsiballZ_mm_dnsrecord.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/hollisma/.ansible/tmp/ansible-tmp-1622855131.6394677-110818-22478518117393/AnsiballZ_mm_dnsrecord.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.mm_dnsrecord', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_mm_dnsrecord_payload_926tdi80/ansible_mm_dnsrecord_payload.zip/ansible/modules/mm_dnsrecord.py\", line 377, in <module>\n  File \"/tmp/ansible_mm_dnsrecord_payload_926tdi80/ansible_mm_dnsrecord_payload.zip/ansible/modules/mm_dnsrecord.py\", line 373, in main\n  File \"/tmp/ansible_mm_dnsrecord_payload_926tdi80/ansible_mm_dnsrecord_payload.zip/ansible/modules/mm_dnsrecord.py\", line 260, in run_module\nAttributeError: module 'include' has no attribute 'get_single_refs'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}`

`
---
- name: Men&Mice DNSRecord test play
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Ansible information
      debug:
        msg:
          - "Ansible version   : {{ ansible_version.full }}"
          - "Python version    : {{ ansible_facts['python_version'] }}"
          - "Python executable : {{ ansible_facts['python']['executable'] }}"

    - name: Set DNS record
      mm_dnsrecord:
        state: present
        name: ansible-test
        rrtype: A
        dnszone: test.com
        data: 10.10.10.10
        comment: From The API side
        ttl: 86400
        provider:
          mmurl: xxxxxxxxxx
          user: xxxxxxxxxxx
          password: xxxxxxxxx
      delegate_to: localhost
`

**Comment by Martin-Metz** [comment]
Hi Marshall, I think our documentation needs some update. 
If you copy the modules directly from the src it will not work.

To install the modules just "cd" into the "src" directory inside of the package, i.e.
ansible-module/ansible/src

Then run there ./doit
which will merge and copy the standalone modules to
ansible-module/ansible/library
Then copy all mm*.py files over to your modules directory (or just the one you used (mm_dnsrecord.py).
The files contain then the missing function get_single_ref

Please check out:
https://github.com/menandmice/ansible-module/blob/master/ansible/src/README.adoc
Thanks!

**Comment by slientnight** [comment]
Thanks. I looked through the docs and missed that part. The above did the trick.
